[package]
name = "async-mesos"
version = "0.1.0"
authors = ["Karsten Jeschkies <jeskar@web.de>"]

[dependencies]
bytes = "0.4"
failure = "0.1"
futures = "0.1"
hyper = "0.11"
protobuf = { version = "1.4", features = ["with-bytes"] }
spectral = "0.6"
tokio-core = "0.1"
